const plates = [
  {
    id: 1,
    src: require("../assets/ishihara/plate1.png"),
    correct: ["35"],
    protanopia: ["3", ""],
    deuteranopia: ["3", "33"],
  },
  {
    id: 2,
    src: require("../assets/ishihara/plate2.png"),
    correct: ["15"],
    protanopia: [""],
    deuteranopia: ["1", "13"],
  },
  {
    id: 3,
    src: require("../assets/ishihara/plate3.png"),
    correct: ["2"],
    protanopia: [""],
    deuteranopia: ["33"],
  },
  {
    id: 4,
    src: require("../assets/ishihara/plate4.png"),
    correct: ["12"],
    protanopia: ["12"],
    deuteranopia: ["12"],
  },
  {
    id: 5,
    src: require("../assets/ishihara/plate5.png"),
    correct: ["16"],
    protanopia: [""],
    deuteranopia: ["16"],
  },
  {
    id: 6,
    src: require("../assets/ishihara/plate6.png"),
    correct: ["97"],
    protanopia: [""],
    deuteranopia: [""],
  },
  {
    id: 7,
    src: require("../assets/ishihara/plate7.png"),
    correct: ["3"],
    protanopia: [""],
    deuteranopia: ["3"],
  },
  {
    id: 8,
    src: require("../assets/ishihara/plate8.png"),
    correct: ["45"],
    protanopia: [""],
    deuteranopia: [""],
  },
  {
    id: 9,
    src: require("../assets/ishihara/plate9.png"),
    correct: ["42"],
    protanopia: ["", "6"],
    deuteranopia: ["4", "42", "49"],
  },
  {
    id: 10,
    src: require("../assets/ishihara/plate10.png"),
    correct: ["29"],
    protanopia: ["20", ""],
    deuteranopia: ["29"],
  },
  {
    id: 11,
    src: require("../assets/ishihara/plate11.png"),
    correct: ["74"],
    protanopia: [""],
    deuteranopia: ["81", "84", ""],
  },
  {
    id: 12,
    src: require("../assets/ishihara/plate12.png"),
    correct: ["26"],
    protanopia: ["2", ""],
    deuteranopia: ["2", "26", "28"],
  },
  {
    id: 13,
    src: require("../assets/ishihara/plate13.png"),
    correct: ["57"],
    protanopia: [""],
    deuteranopia: ["57", ""],
  },
  {
    id: 14,
    src: require("../assets/ishihara/plate14.png"),
    correct: ["7"],
    protanopia: [""],
    deuteranopia: ["7"],
  },
  {
    id: 15,
    src: require("../assets/ishihara/plate15.png"),
    correct: ["73"],
    protanopia: [""],
    deuteranopia: ["73"],
  },
];

export default plates;
